### ISSUE TITLE
Textbox validation: equal not working

### ISSUE THREAD

**Issue by davidsavoie1** [ManuelDeLeon/viewmodel-react-plugin#3]
Hi! The `equal` validation segment of an integer property doesn't seem to be working. If I copy a part of the [validation section example](https://viewmodel.org/react#AdvancedValidation) from the documentation and modify `min(18)` for `equal(18)`, the field is always displayed as an error even if I write 18. Of course, same thing with `notEqual`. 

**It does work if I use `equal('18')` (with quotes), but it's counterintuitive since I'm expecting a number.**

Here's the simplified code:
```
Example({
  age: ViewModel.property.integer.equal(18)
    .default("") // Override the default value of zero
    .invalidMessage("Must be at least 18 years old")
    .validMessage("Is an adult (at least legally)"),
  
  render() {
    <form class="ui form">
      <div class="field" b="class: { error: age.invalid }">
        <label>Age</label>
        <div class="ui icon input " >
          <input type="text" b="value: age, attr: { title: age.message }" />
          <i class="thumbs down outline icon" b="if: age.invalid" />
        </div>
      </div>
    </form>
  },
});
```
Thanks!

**Comment by ManuelDeLeon** [comment]
Update to `viewmodel-react v2.4.1`
Thanks
